### ISSUE TITLE
33| DE | Cases and Contacts | Option to document that quarantine talk took place with date and comment field

### ISSUE THREAD

**Issue by Candice-Louw** [Candice-Louw/SORMAS.DE#1]
### Problem Description ###
As a Gesundheitsamt reporter I would like to indicate that a discussion about quarantine has taken place (check-box) 
with a case/contact on a specific date (date selector field) and add further comments to the discussion if necessary (free-type text box).

### Steps to Reproduce ###
Steps to reach section:
Cases > Select case > Case Information: CASE tab > scroll down to "Quarantine"
Contacts > Select contact > Contact Information: CONTACT tab > scroll down to "Quarantine"

### Suggested Addition ###
Addition of 'quarantine discussion' drop-down field.  

Options in drop-down field: 
(DE)> " ", Ja, Nein, -nicht ermittelbar-
(EN)> " ", Yes, No, Unknown

IF "Ja/Yes" answered in drop-down field do the following
{
Make date field visible with caption: "Date of quarantine discussion".
Make free-text comment field visible with caption: "Comments".
}

### Screenshots ###
<img width="1146" alt="QuarantineDiscussion" src="https://user-images.githubusercontent.com/65529128/88832399-0cb85b00-d1d1-11ea-9a1e-8b4b6b2dbaa4.png">

**Comment by Candice-Louw** [comment]
Related to https://github.com/hzi-braunschweig/SORMAS-Project/issues/2577 ?

**Comment by GabrielePoggensee** [comment]
Yes, the topic is covered.
