### ISSUE TITLE
DE | Archiving case and case contacts only after quarantine for contacts is complete

### ISSUE THREAD

**Issue by Candice-Louw** [Candice-Louw/SORMAS.DE#3]
### Reporting Origin ###
Hotline

### Problem Description ###

**DE:**
Sehr geehrte Damen und Herren,
 
Sormas ist so programmiert, dass bei der Archivierung eines Falles alle damit verbundenen Kontakte automatisch mit archiviert werden.
 
Das ist äußerst unpraktisch, da nach den Richtlinien des RKI Fälle üblicherweise schneller aus der Quarantäne entlassen werden als Kontakte. Das heißt, man kann den Fall nach Quarantänebeendigung nicht sofort archivieren, weil man dann die automatisch mit archivierten aber real noch in Quarantäne befindlichen Kontakte nicht mehr bearbeiten kann. Deshalb muss man den Fall noch aktiv lassen und sich extra merken, dass man ihn erst archivieren kann, wenn alle damit verbundenen Kontakte aus der Nachverfolgung entlassen sind.

Einfacher wäre es, wenn man den Fall einzeln archivieren kann ohne dass dies Auswirkungen auf die Kontakte hat. Die Kontakte werden bei Abbruch der Nachverfolgung wie bisher automatisch archiviert.

**EN:**
Dear Sir or Madam,
 
Sormas is programmed so that when a case is archived, all associated contacts are automatically archived.
 
This is extremely impractical, because according to the guidelines of the RKI, cases are usually released from quarantine faster than contacts. This means that the case cannot be archived immediately after the quarantine has ended, because it is then no longer possible to process the contacts that are automatically archived but actually still in quarantine. Therefore, you have to keep the case active and remember that you can only archive it when all the contacts associated with it have been released from follow-up.

It would be easier if you could archive the case individually without affecting the contacts. The contacts will be automatically archived when tracking is canceled.

**Comment by GabrielePoggensee** [comment]
Very valid observation from Berlin. The simultaneous archiving of the contacts of a case when archiving a case is not a clean procedure as cases and contacts have different "properties"

**Comment by Candice-Louw** [comment]
Advised client to not Archive cases purposefully to avoid this problem from occurring.
